language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - build-tools-29.0.2
  - build-tools-30.0.3
  - android-29
  - android-30  
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - ./gradlew build
